<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GunungSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('gunung')->insert([
            [
                'nama_gunung' => 'Gunung Semeru',
                'lokasi' => 'Lumajang, Jawa Timur',
                'ketinggian' => 3676,
                'harga_simaksi' => 25000,
                'deskripsi' => 'Gunung tertinggi di Pulau Jawa dengan pemandangan Ranu Kumbolo yang menakjubkan.',
                'gambar' => 'Gunung_semeru.jpg',
                'latitude' => -8.1086,
                'longitude' => 112.9227,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Rinjani',
                'lokasi' => 'Lombok, Nusa Tenggara Barat',
                'ketinggian' => 3726,
                'harga_simaksi' => 35000,
                'deskripsi' => 'Gunung terkenal dengan Danau Segara Anak dan panorama matahari terbit yang luar biasa.',
                'gambar' => 'GunungRinjani.jpg',
                'latitude' => -8.4117,
                'longitude' => 116.4578,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Bromo',
                'lokasi' => 'Probolinggo, Jawa Timur',
                'ketinggian' => 2329,
                'harga_simaksi' => 20000,
                'deskripsi' => 'Gunung aktif dengan kawah yang menakjubkan dan lautan pasir yang ikonik.',
                'gambar' => 'GunungBromo.jpg',
                'latitude' => -7.9425,
                'longitude' => 112.9533,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Merapi',
                'lokasi' => 'Sleman, Yogyakarta',
                'ketinggian' => 2930,
                'harga_simaksi' => 15000,
                'deskripsi' => 'Gunung berapi paling aktif di Indonesia dengan jalur pendakian yang menantang.',
                'gambar' => 'GunungMerapi.jpg',
                'latitude' => -7.5408,
                'longitude' => 110.4461,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Merbabu',
                'lokasi' => 'Magelang, Jawa Tengah',
                'ketinggian' => 3145,
                'harga_simaksi' => 20000,
                'deskripsi' => 'Gunung dengan padang sabana dan panorama puncak Kenteng Songo yang indah.',
                'gambar' => 'GunungMerbabu.jpg',
                'latitude' => -7.4558,
                'longitude' => 110.4375,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Sindoro',
                'lokasi' => 'Temanggung, Jawa Tengah',
                'ketinggian' => 3150,
                'harga_simaksi' => 18000,
                'deskripsi' => 'Gunung dengan kawah belerang aktif dan pemandangan perkebunan teh yang luas.',
                'gambar' => 'GunungSindoro.jpg',
                'latitude' => -7.3025,
                'longitude' => 109.9967,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Sumbing',
                'lokasi' => 'Wonosobo, Jawa Tengah',
                'ketinggian' => 3371,
                'harga_simaksi' => 20000,
                'deskripsi' => 'Gunung kembar dari Sindoro, terkenal dengan jalur pendakian menantang dan pemandangan spektakuler.',
                'gambar' => 'Sindoro_Sumbing.jpg',
                'latitude' => -7.3842,
                'longitude' => 109.9242,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Lawu',
                'lokasi' => 'Karanganyar, Jawa Tengah',
                'ketinggian' => 3265,
                'harga_simaksi' => 22000,
                'deskripsi' => 'Gunung bersejarah dengan jalur pendakian yang populer seperti Cemoro Sewu dan Cemoro Kandang.',
                'gambar' => 'GunungLawu.jpg',
                'latitude' => -7.6292,
                'longitude' => 111.1933,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Prau',
                'lokasi' => 'Dieng, Jawa Tengah',
                'ketinggian' => 2565,
                'harga_simaksi' => 15000,
                'deskripsi' => 'Gunung populer di kalangan pendaki pemula, terkenal dengan lautan awan dan sunrise terbaik.',
                'gambar' => 'GunungPrau.jpg',
                'latitude' => -7.1892,
                'longitude' => 109.9242,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Kerinci',
                'lokasi' => 'Jambi, Sumatera',
                'ketinggian' => 3805,
                'harga_simaksi' => 40000,
                'deskripsi' => 'Gunung tertinggi di Sumatera dan salah satu puncak Seven Summits Indonesia.',
                'gambar' => 'Gunung_Kerinci.png',
                'latitude' => -1.6967,
                'longitude' => 101.2642,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Ciremai',
                'lokasi' => 'Kuningan, Jawa Barat',
                'ketinggian' => 3078,
                'harga_simaksi' => 20000,
                'deskripsi' => 'Gunung tertinggi di Jawa Barat, dengan hutan lebat dan jalur pendakian Apuy serta Linggarjati.',
                'gambar' => 'GunungCeremai.jpg',
                'latitude' => -6.8933,
                'longitude' => 108.4008,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Arjuno',
                'lokasi' => 'Malang, Jawa Timur',
                'ketinggian' => 3339,
                'harga_simaksi' => 25000,
                'deskripsi' => 'Gunung dengan pemandangan indah dan jalur klasik Tretes serta Lawang.',
                'gambar' => 'arjuno.jpg',
                'latitude' => -7.7258,
                'longitude' => 112.5892,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_gunung' => 'Gunung Papandayan',
                'lokasi' => 'Garut, Jawa Barat',
                'ketinggian' => 2665,
                'harga_simaksi' => 18000,
                'deskripsi' => 'Gunung dengan kawah aktif dan hutan mati yang menjadi daya tarik wisata utama.',
                'gambar' => 'gunung gede.jpg',
                'latitude' => -7.3217,
                'longitude' => 107.7308,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
